name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details about your idea.
        
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Game
        - Framework Enhancement
        - UI/UX Improvement
        - Multiplayer Feature
        - AI Enhancement
        - Accessibility
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the problem or use case this feature would address
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe alternatives you've considered
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Any other information that would help understand your request
    validations:
      required: false
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'd like to work on implementing this feature
        - label: I can help with testing and feedback
        - label: I can help with documentation